### ISSUE TITLE
Control for variables of no interest?

### ISSUE THREAD

**Issue by johnaeanderson** [derekbeaton/GPLS#8]
Hi Derek,

Is it possible to do something like a partial correlation (e.g., hold some variables constant) in the GPLS framework?

Thanks!

**Comment by derekbeaton** [comment]
Thanks for asking, John. Because this turned into a statistical conversation via email, I will close the issue here for now. Though your question is something that will (eventually...) end up as part of the vignettes on small data. For now (and for future others), please also see the second and third examples in the manuscript for an approach of regressing out effects and then performing analyses between two data sets that were orthogonalized by some additional covariates
